---
- name: install base packages
  become: true
  yum:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - nano
    - createrepo

- name: create splunk repo
  become: true
  command: createrepo /vagrant/repo/
  args:
    creates: /vagrant/repo/repodata

- name: register splunk repo
  stat:
    path: /etc/yum.repos.d/splunk.repo
  register: splunk_repo

- name: add a local splunk repository
  become: true
  yum_repository:
    reposdir: /etc/yum.repos.d
    name: splunk-repo
    description: Splunk
    file: splunk
    baseurl: file:///vagrant/repo
    gpgcheck: no
    enabled: yes
