---
# cluster nodes
domain_name: uat.avocado.lab
clm_servers:
  clm01:
    name: "clm01.{{ domain_name }}"
shd_servers:
  shd01:
    name: "shd01.{{ domain_name }}"
idx_servers:
  idx01:
    name: "idx01.{{ domain_name }}"
  idx02:
    name: "idx02.{{ domain_name }}"

splunk:
  home: /opt/splunk
  user: splunk
  group: splunk
  man:
    port: 8089
  web:
    port: 8000
  rep:
    port: 9887

# replication settings
cluster:
  replication_factor:               2
  search_factor:                    1
  access_logging_for_heartbeats:    1
  max_peer_build_load:              5
  pass4SymmKey:                     test.123
  label:                            "{{ domain_name }}"
  role:
    clm: master
    idx: slave
    shd: searchhead
